In [1]:
%matplotlib inline
import numpy as np
import pandas as pd


np.random.seed(29)



##1. How likely is it that you roll doubles when rolling two dice?

n_trials = nrows = 10_000
n_dice = ncols = 2

roll1 = np.random.choice([1,2,3,4,5,6], n_trials * n_dice).reshape(nrows,ncols)
roll2 = np.random.choice([1,2,3,4,5,6], n_trials * n_dice).reshape(nrows,ncols)
doubles = (roll1 == roll2).mean()

doubles
print(f'The probability to roll doubles is {doubles}')




The probability to roll doubles is 0.16585


In [2]:
##2. If you flip 8 coins, what is the probability of getting exactly 3 heads? 
##What is the probability of getting more than 3 heads?

n_trials = nrows = 10_000
n_coins = ncols = 8
result = np.random.choice(['heads', 'tails'], n_trials * n_coins).reshape(nrows,ncols)# Calculates the posibilities
heads = (result == 'heads').sum(axis =1)# extracts the heads possibilities


three_heads = (heads ==3).mean()# calculates the possibilities of 3 heads
three_heads



0.2234

In [3]:
n_trials = nrows = 10_000
n_coins = ncols = 8
result = np.random.choice(['heads', 'tails'], n_trials * n_coins).reshape(nrows,ncols)
heads = (result == 'heads').sum(axis =1)


greater_heads = (heads >3).mean()# calculates the possibilities of more then 3 heads
greater_heads

0.6292

In [4]:
##3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup.
##Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

n_trials = nrows = 10_000
n_billb = ncols = 2
result = np.random.choice(['Data Science', 'WD'], n_trials * n_billb).reshape(nrows,ncols)## selects random options from a list (Data science or Web dev)
dsresults = (result == 'Data Science').sum(axis =1)
ds = (dsresults ==2).mean()## takes the result of "data science" that will go on both billboards

ds

0.2505

In [5]:
##4. Codeup students buy, on average, 3 poptart packages (+- 1.5) a day from the snack vending machine. 
## If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon?
poptart_avg = 3 ## average of 3 pop tarts a day
poptart_stdev = 1.5 ## standard deviation of 1.5 a day
n_trials = nrows = 10_000
n_days = ncols = 5

pt_bought = np.random.normal(poptart_avg,poptart_stdev,size=(n_trials,n_days)) ## generates numbers from a normal distribution with a specified mean and standard deviation
pt_bought



array([[-1.3046932 ,  2.89493903,  3.79928835,  5.3332525 ,  2.10855049],
       [ 1.6490071 ,  1.3831255 ,  2.74386621,  3.52071587,  1.29916504],
       [ 4.76238865,  3.3038519 ,  3.54816728,  1.50750822,  4.54018916],
       ...,
       [ 4.9496596 ,  3.70212711,  3.8470058 ,  2.6144602 ,  1.40257486],
       [ 6.12295443,  2.0400103 ,  3.80985904,  0.52613549,  3.53711225],
       [ 2.36889002,  4.91963779,  2.86555797,  3.85229814,  1.83121109]])

In [6]:
pt_on_friday = 17 - pt_bought.sum(axis =1)## subtracts total number from restock on monday
pt_on_friday

array([ 4.16866283,  6.40412029, -0.6621052 , ...,  0.48417244,
        0.9639285 ,  1.16240499])

In [34]:
(pt_on_friday >0).mean()

0.7254

In [8]:
##5. Compare Heights

##Men have an average height of 178 cm and standard deviation of 8cm.
##Women have a mean of 170, sd = 6cm.
##Since you have means and standard deviations, you can use np.random.normal to generate observations.
##If a man and woman are chosen at random, P(woman taller than man)?


mheight_avg = 178
mheight_stdev = 8

wheight_avg = 170
wheight_stdev = 6

n_trials = nrows = 10_000
n_subj = ncols = 2

mstats = np.random.normal(mheight_avg,mheight_stdev,size=(n_trials,n_subj)) ## generates numbers from a normal distribution with a specified mean and standard deviation
mstats

wstats = np.random.normal(wheight_avg,wheight_stdev,size=(n_trials,n_subj)) ## generates numbers from a normal distribution with a specified mean and standard deviation
wstats

wtaller = (wstats > mstats).mean()## checks to see at random woman taller then man
wtaller

0.21425

In [9]:
##6. When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. 
##What are the odds that after having 50 students download anaconda, 

1/250 # chance of fail


##no one has an installation issue? 100 students?

0.004

In [10]:
1-(1/250) ## success

0.996

In [11]:
result = [1,0]

fifty_successes = np.random.choice(result, size = (10_000,50),p=(.996,.004))## creates an array of choice between 0 and 1
fifty_successes




array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [12]:
fifty_successes_prob = fifty_successes.sum(axis=1) 
(fifty_successes_prob ==50).mean()## average success of the probability equals to 50

0.8183

In [13]:
##no one has an installation issue? 100 students?

hund_successes = np.random.choice(result, size = (10_000,100),p=(.996,.004))
hund_successes


hund_successes_prob = hund_successes.sum(axis=1) 
(hund_successes_prob ==100).mean()## average success of the probability equals to 100

0.6742

In [14]:
## What is the probability that we observe an installation issue within the first 150 students that download anaconda?


result = [1,0]
download_error = np.random.choice(result, size = (10_000,150),p=(.996,.004))
fail_prob = download_error.sum(axis=1)
(fail_prob <150).mean()




0.4514

In [15]:
##How likely is it that 450 students all download anaconda without an issue?

result = [1,0]
download_error = np.random.choice(result, size = (10_000,450),p=(.996,.004))
fail_prob = download_error.sum(axis=1)
(fail_prob == 450).mean()



0.167

In [16]:
## 7.There's a 70% chance on any given day that there will be at least one food truck at Travis Park. 
##However, you haven't seen a food truck there in 3 days. How unlikely is this?

result=[1,0]
food = np.random.choice(result, size =(10_000,3), p=(.70,.30))
prob_no_food = food.sum(axis=1)
(prob_no_food ==0).mean()


0.029

In [17]:
##How likely is it that a food truck will show up sometime this week?

food = np.random.choice(result, size =(10_000,7), p=(.70,.30))
prob_no_food = food.sum(axis=1)
(prob_no_food >=1).mean()


0.9998

In [18]:
##If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?


data = range(0,365)
ntrials = 23
nsimulations = 10_000

rooms = np.random.choice(data, size= (nsimulations, ntrials))
rooms


array([[294,  91,  96, ..., 234, 326, 173],
       [315, 198,  71, ..., 242,  10, 342],
       [ 81,  37, 185, ..., 197, 256,  70],
       ...,
       [  8, 186, 118, ..., 200,  21, 294],
       [ 14, 319, 116, ..., 173, 298, 258],
       [120,  81, 296, ..., 294,  87,  73]])

In [19]:
list_double_bdays = [len(np.unique(rooms[n])) for n in range(0, nsimulations-1) if len(np.unique(rooms[n])) < 23]
list_double_bdays

[22,
 22,
 21,
 22,
 22,
 22,
 21,
 22,
 22,
 22,
 22,
 20,
 22,
 22,
 22,
 22,
 22,
 22,
 22,
 21,
 21,
 22,
 21,
 21,
 22,
 22,
 22,
 22,
 20,
 22,
 22,
 22,
 22,
 21,
 22,
 22,
 22,
 22,
 22,
 22,
 22,
 22,
 22,
 22,
 22,
 22,
 22,
 22,
 22,
 21,
 22,
 22,
 21,
 22,
 22,
 22,
 22,
 22,
 22,
 22,
 22,
 21,
 21,
 22,
 22,
 22,
 21,
 22,
 19,
 22,
 22,
 22,
 22,
 22,
 22,
 22,
 21,
 21,
 22,
 22,
 21,
 22,
 21,
 22,
 20,
 22,
 22,
 22,
 22,
 22,
 22,
 22,
 22,
 22,
 21,
 21,
 22,
 21,
 21,
 22,
 21,
 21,
 21,
 22,
 22,
 22,
 21,
 21,
 22,
 22,
 21,
 22,
 20,
 20,
 22,
 22,
 22,
 21,
 21,
 21,
 22,
 22,
 22,
 21,
 22,
 22,
 22,
 22,
 22,
 22,
 22,
 22,
 21,
 21,
 22,
 21,
 22,
 22,
 22,
 21,
 21,
 22,
 21,
 22,
 22,
 21,
 22,
 22,
 21,
 19,
 22,
 22,
 22,
 22,
 21,
 22,
 22,
 22,
 22,
 21,
 22,
 22,
 21,
 22,
 21,
 22,
 21,
 21,
 22,
 22,
 22,
 22,
 21,
 21,
 21,
 21,
 21,
 22,
 20,
 22,
 20,
 22,
 22,
 22,
 22,
 20,
 22,
 21,
 21,
 22,
 22,
 22,
 21,
 22,
 21,
 22,
 22,
 22,
 22,
 22,


In [20]:
same_bdays = len(list_double_bdays) / nsimulations
same_bdays

0.5119

In [30]:
data = range(0,365)
ntrials = 40
nsimulations = 10_000

rooms = np.random.choice(data, size= (nsimulations, ntrials))
rooms

list_double_bdays = [len(np.unique(rooms[n])) for n in range(0, nsimulations-1) if len(np.unique(rooms[n])) < 40]
list_double_bdays

[38,
 37,
 39,
 38,
 36,
 39,
 39,
 38,
 37,
 38,
 38,
 39,
 38,
 38,
 38,
 38,
 37,
 34,
 39,
 36,
 37,
 39,
 38,
 39,
 37,
 39,
 36,
 38,
 39,
 38,
 39,
 39,
 37,
 39,
 39,
 38,
 36,
 38,
 39,
 39,
 39,
 39,
 37,
 37,
 36,
 36,
 39,
 38,
 39,
 38,
 38,
 38,
 39,
 38,
 37,
 39,
 38,
 37,
 39,
 37,
 39,
 39,
 39,
 39,
 37,
 37,
 38,
 39,
 38,
 38,
 37,
 38,
 39,
 36,
 37,
 38,
 38,
 37,
 37,
 39,
 39,
 38,
 37,
 38,
 37,
 39,
 38,
 38,
 36,
 38,
 35,
 38,
 39,
 39,
 36,
 37,
 37,
 36,
 38,
 39,
 38,
 37,
 34,
 38,
 37,
 38,
 37,
 38,
 38,
 37,
 39,
 37,
 39,
 36,
 37,
 38,
 39,
 39,
 37,
 37,
 37,
 37,
 38,
 39,
 36,
 38,
 38,
 38,
 36,
 39,
 37,
 39,
 38,
 39,
 39,
 36,
 39,
 36,
 39,
 39,
 37,
 36,
 38,
 39,
 38,
 39,
 38,
 38,
 39,
 38,
 36,
 36,
 39,
 35,
 36,
 38,
 32,
 38,
 38,
 37,
 39,
 38,
 38,
 35,
 39,
 39,
 36,
 37,
 38,
 37,
 39,
 38,
 39,
 38,
 36,
 38,
 37,
 39,
 37,
 37,
 39,
 34,
 37,
 39,
 38,
 38,
 38,
 36,
 39,
 39,
 37,
 38,
 39,
 37,
 38,
 35,
 38,
 39,
 39,
 36,


In [31]:
same_bdays = len(list_double_bdays) / nsimulations
same_bdays

0.8925

In [35]:
data = range(0,365)
ntrials = 20
nsimulations = 10_000

rooms = np.random.choice(data, size= (nsimulations, ntrials))
rooms

list_double_bdays = [len(np.unique(rooms[n])) for n in range(0, nsimulations-1) if len(np.unique(rooms[n])) < 20]
list_double_bdays

[19,
 19,
 18,
 19,
 18,
 19,
 19,
 19,
 18,
 17,
 19,
 19,
 18,
 19,
 19,
 19,
 18,
 19,
 19,
 19,
 18,
 19,
 19,
 19,
 17,
 18,
 18,
 19,
 19,
 19,
 19,
 19,
 19,
 18,
 19,
 19,
 18,
 19,
 19,
 19,
 19,
 19,
 19,
 19,
 19,
 19,
 19,
 19,
 19,
 19,
 19,
 19,
 19,
 18,
 19,
 19,
 19,
 19,
 19,
 19,
 19,
 18,
 18,
 19,
 19,
 19,
 19,
 19,
 19,
 19,
 19,
 19,
 18,
 19,
 19,
 19,
 19,
 18,
 19,
 19,
 19,
 19,
 18,
 19,
 19,
 19,
 19,
 19,
 18,
 19,
 18,
 17,
 19,
 19,
 19,
 19,
 19,
 18,
 19,
 19,
 19,
 19,
 18,
 19,
 19,
 19,
 19,
 19,
 18,
 19,
 19,
 19,
 19,
 19,
 19,
 19,
 18,
 17,
 19,
 19,
 19,
 19,
 19,
 19,
 18,
 18,
 19,
 19,
 19,
 19,
 19,
 19,
 19,
 19,
 19,
 19,
 18,
 19,
 19,
 16,
 19,
 19,
 19,
 19,
 19,
 18,
 19,
 19,
 19,
 19,
 19,
 18,
 19,
 19,
 19,
 19,
 19,
 19,
 19,
 18,
 19,
 19,
 19,
 19,
 19,
 19,
 17,
 19,
 19,
 19,
 18,
 19,
 19,
 19,
 18,
 19,
 19,
 19,
 19,
 19,
 18,
 19,
 19,
 19,
 19,
 19,
 18,
 19,
 18,
 19,
 19,
 19,
 19,
 19,
 19,
 19,
 19,
 19,
 19,
 18,


In [36]:
same_bdays = len(list_double_bdays) / nsimulations
same_bdays

0.4131